excerpt_separator: <!--excerpt-->
title: Ripto's Rankings
description: 'Every Spyro 2 level, ranked'
selection:
  option1: OPTION ONE
  option2: OPTION TWO
  option3: OPTION THREE
collections:
  levels:
    title: Levels
    output: true
    image: /uploads/big-pine-landscape.jpg
    description: >-
      Here is a lot of text describing this collection. Levels is an avicii
      song.
  awards:
    title: Awards
    icon: people
  stuff:
    title: Stuff
  collecties:
    output: true
_array_structures:
  test_array:
    - label: Recursive
      value:
        name: Recursive Option
        test_array: null
    - label: Option 2
      value:
        name: One
    - label: Option 3
      value:
        name: One
    - label: Option 4
      value:
        name: One
    - label: Option 5
      value:
        name: One
    - label: Option 6
      value:
        name: One
    - label: Option 7
      value:
        name: One
    - label: Option 8
      value:
        name: One
    - label: Option 9
      value:
        name: One
    - label: Option 10
      value:
        name: One
    - label: Option 11
      value:
        name: One
    - label: Option 12
      value:
        name: One
    - label: Option 13
      value:
        name: One
    - label: Option 14
      value:
        name: Option One
defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: ''
      type: levels
    values:
      layout: level
      _comments:
        title: The page title
        chron_order: Indicates where this level should sit in an ordered list
_options:
  content:
    code: true
    embed: true
    link: true
    table: true
  image_path:
    uploads_dir: 'images/:title/'
    resize_style: stretch
  sky_image_path:
    uploads_dir: 'images/:title/'
    resize_style: cover
plugins:
  - jekyll-feed
  - jekyll-seo-tag
feed:
  collections:
    - awards
    - levels
