excerpt_separator: "<!--excerpt-->"

title: Ripto's Rankings
description: Every Spyro 2 level, ranked

selection:
  op1: OPTION ONE
  op2: OPTION TWO
  op3: OPTION THREE

collections:
  levels:
    output: true
  awards:

_array_structures:
  test_array:
    - label: "Option 1"
      value:
        name: "One"
    - label: "Option 2"
      value:
        name: "One"
    - label: "Option 3"
      value:
        name: "One"
    - label: "Option 4"
      value:
        name: "One"
    - label: "Option 5"
      value:
        name: "One"
    - label: "Option 6"
      value:
        name: "One"
    - label: "Option 7"
      value:
        name: "One"
    - label: "Option 8"
      value:
        name: "One"
    - label: "Option 9"
      value:
        name: "One"
    - label: "Option 10"
      value:
        name: "One"
    - label: "Option 11"
      value:
        name: "One"
    - label: "Option 12"
      value:
        name: "One"
    - label: "Option 13"
      value:
        name: "One"
    - label: "Option 14"
      value:
        name: "Option One"

defaults:
  - 
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "levels"
    values:
      layout: "level"
      _comments:
        title: The page title
        chron_order: Indicates where this level should sit in an ordered list

_options:
  content:
    embed: true
  image_path:
    uploads_dir: "images/:title/"
    resize_style: "stretch"
  sky_image_path:
    uploads_dir: "images/:title/"
    resize_style: "cover"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

feed:
  collections:
    - awards
    - levels