excerpt_separator: "<!--excerpt-->"

title: Ripto's Rankings
description: Every Spyro 2 level, ranked

include: _schedule.txt

collections:
  levels:
    output: true
  awards:

defaults:
  - 
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "levels"
    values:
      layout: "level"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

feed:
  collections:
    - awards
    - levels