excerpt_separator: "<!--excerpt-->"

title: Ripto's Rankings
description: Every Spyro 2 level, ranked

collections:
  levels:
    output: true
  awards:

defaults:
  - 
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "levels"
    values:
      layout: "level"

_source_editor:
  theme: dracula

_options:
  image_path:
    uploads_dir: "images/:title/"
  sky_image_path:
    uploads_dir: "images/:title/"
  images/:
    width: 100
    height: 100
    resize_style: "contain"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

feed:
  collections:
    - awards
    - levels