excerpt_separator: "<!--excerpt-->"

collections:
  levels:
    output: true
  awards:

defaults:
  - 
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "levels"
    values:
      layout: "level"