excerpt_separator: "<!--excerpt-->"

title: Ripto's Rankings
description: Every Spyro 2 level, ranked

collections:
  levels:
    output: true
  awards:

defaults:
  - 
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "levels"
    values:
      layout: "level"
      _comments:
        title: The page title
        chron_order: Indicates where this level should sit in an ordered list
  -
    scope:
      path: ""
      type: "tests"
    values:
      layout: "test"

_options:
  image_path:
    uploads_dir: "images/:title/"
    resize_style: "stretch"
  sky_image_path:
    uploads_dir: "images/:title/"
    resize_style: "cover"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

feed:
  collections:
    - awards
    - levels